### PR TITLE
Fix Crash When No Params Are Passed

### PR DESCRIPTION
**Pull request by coreyphillips**
This PR adds a condition to check for params in TargetComponent and resolves the crash that would occur if no params were passed.

### CODE REVIEW

**Comment by vonovak** [comment]
hello, and thanks for the PR. When does such crash happen? I was under the impression that route.params is always defined. Thanks!

**Comment by coreyphillips** [comment]
np! As I was incorrectly experimenting with the library I discovered that if it was used outside of `Stack.Screen` it would throw due to `params` being undefined. However, if the library is used correctly then this error should never occur.

**Comment by vonovak** [comment]
hmm, okay then maybe the right approach is 

(1) not to crash - as done in this PR
(2) warn the user about usage that is incorrect

What do you think?

**Comment by coreyphillips** [comment]
Probably shouldn't have said incorrectly. Exporting it straight from the component itself is more unintended use. There may be a situation where a dev may want or need to set it and forget it in the event they use it in a stack and as a component outside the navigator stack. Though it's probably best to discourage that with an error anyway.

**Pull request closed without merging**
