### PR TITLE
update params access to match v5 of react-navigation

### PR DESCRIPTION
**Pull request by hossamnasser938**

### CODE REVIEW

**Comment by vonovak** [comment]
thank you for the PR!

**Comment by vonovak** [comment]
some extra work is needed to make this work but I'll do a release this week.

**Comment by hossamnasser938** [comment]
@vonovak  You're welcome. If I can do something, I'm open for help

**Comment by vonovak** [comment]
@hossamnasser938 I already released this so you can test it out :)

**Pull request merged**
