### PR TITLE
handle empty params in TargetComponent

### PR DESCRIPTION
**Pull request by ruslan-hontar**
- added condition to check for empty params in `TargetComponent`. return empty object, otherwise.

this pr contains fix for empty params. in some cases useful to use the same component as a screen inside the navigator and as a screen for the modal window. for the second variant `props.route` will not contain `params`. to handle this and left `withForwardedNavigationParams` i added a checker for empty `params`

<details>
  <summary>Screenshot  with error</summary>
  
image
  
</details>

### CODE REVIEW

**Comment by vonovak** [comment]
hello and thank you for the PR!

> in some cases useful to use the same component as a screen inside the navigator and as a screen for the modal window

can you please expand on what you mean by this? I'm not sure I follow. Can you share a code snippet? Thank you :)

**Comment by ruslan-hontar** [comment]
@vonovak 
[here](https://snack.expo.dev/@kef/react-navigation-props-mapper) snack with reproducing an error
- in the `Navigation` folder just simple stack with 2 screens
- in the screens just two screens
- `Second` screen receives `screenName` prop from the navigation params in some cases, otherwise just renders other text
- `First` screen contains two buttons:
  - `Go to the new screen` works fine with navigation params inside
  - `Open Modal` uses the same screen (`Second`) as in the navigator. but in this case, we have no `props.route.params` from the navigation and it triggers an error
 
so, in my pr I just check for `params`, otherwise, return empty object
I added `({} as any)` just to handle with ts error, because in general after `props.route` lib also uses `any` type
hope my explanation will be enough

**Comment by vonovak** [comment]
thanks so much for the detailed info. I have fixed it in a different PR that includes a test case for this

**Comment by ruslan-hontar** [comment]
thanks for the implementation

**Pull request closed without merging**
